use_frameworks!

target 'WALL-E' do
  # gRPC
  pod 'EVE', :path => '.'

  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'LayoutKit'
  pod 'Tactile'
  pod 'Kingfisher'
  pod 'R.swift'
  pod 'WXWaveView'
  pod 'YYText'
  pod 'TanImagePicker'
  pod 'JGProgressHUD'
  pod 'Eureka'
  pod 'MessageListener'
end
